name: Dev Build and Deploy on Push
run-name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install MTA Build Tool
        run: npm install -g mbt
      - name: Disable package-lock.json
        run: npm config set package-lock false
      - name: Build MTA
        run: mbt build -p cf
      - name: Upload Artifact
        uses: actions/upload-artifact@master	
        with:	
          name: mta
          path: ./mta_archives/POCGHACTION901_1.0.0.mtar
